server:
  port: 8081

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      delivery-timeout: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

