networks:
  api-network:

volumes:
  auth-db:
  ingest-db:

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      HOME_PAGE: ${HOME_PAGE}
      URL_USER_AUTH_SERVICE: http://user-auth-service:8081
      URL_INGEST_SERVICE: http://ingest-service:8082
      URL_EXAMPLE_SERVICE: http://example-service:8100
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  user-auth-service:
    build: ./user-auth-service
    container_name: user-auth-service
    restart: always
    depends_on:
      auth-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_URI: jdbc:postgresql://auth-db:5432/auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      URL_GATEWAY: ${URL_GATEWAY}
      HOME_PAGE: ${HOME_PAGE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  ingest-service:
    build: ./ingest-service
    container_name: ingest-service
    restart: always
    depends_on:
      ingest-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      QUARKUS_PROFILE: dev
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MYSQL_URI: jdbc:mysql://ingest-db:3306/ingest_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
      - api-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  example-service: # temporary server
    build: ./example-service
    container_name: example-service
    restart: always
    ports:
      - "8100:8100"
    networks:
      - api-network

  auth-db:
    image: postgres:18.0-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingest-db:
    image: mysql:8.1
    container_name: ingest-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ingest_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ingest-db:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8200:8080"
    depends_on:
      - kafka
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - api-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - api-network
    healthcheck:
      test: [ "CMD", "echo", "ru", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
